export const Type = {
  ITEM_DATA_FETCH_START: "ITEM_DATA_FETCH_START",
  ITEM_DATA_FETCH_SUCCESS: "ITEM_DATA_FETCH_SUCCESS",
  ITEM_DATA_FETCH_ERROR: "ITEM_DATA_FETCH_ERROR",

  ITEM_ADD_START: "ITEM_ADD_START",
  ITEM_ADD_SUCCESS: "ITEM_ADD_SUCCESS",
  ITEM_ADD_ERROR: "ERROR",

  ITEM_DELETE_START: "ITEM_DELETE_START",
  ITEM_DELETE_SUCCESS: "ITEM_DELETE_SUCCESS",
  ITEM_DELETE_ERROR: "ITEM_DELETE_ERROR",

  ITEM_UPDATE_START: "ITEM_UPDATE_START",
  ITEM_UPDATE_SUCCESS: "ITEM_UPDATE_SUCCESS",
  ITEM_UPDATE_ERROR: "ITEM_UPDATE_ERROR",
};
