export const Type = {
  // GET_ALL_TASK: "GET_ALL_TASK",
  // DEL_TASK: "DEL_TASK",
  // POST_TASK: "POST_TASK",

ITEMS_ADD:'ITEMS_ADD',

  TASK_DATA_FETCH_START: "TASK_DATA_FETCH_START",
  TASK_DATA_FETCH_SUCCESS: "TASK_DATA_FETCH_SUCCESS",
  TASK_DATA_FETCH_ERROR: "TASK_DATA_FETCH_ERROR",

  TASK_ADD_START: "TASK_ADD_START",
  TASK_ADD_SUCCESS: "TASK_ADD_SUCCESS",
  TASK_ADD_ERROR: "ERROR",

  TASK_DELETE_START: "TASK_DELETE_START",
  TASK_DELETE_SUCCESS: "TASK_DELETE_SUCCESS",
  TASK_DELETE_ERROR: "TASK_DELETE_ERROR",

  GET_AUTH: "GET_AUTH",
};
